import pandas as pd

def analyze_products(df):
    """
    analyze product activity duration, customer reach,
    and revenue for short-duration products.
    """

    # product date range
    product_date_range = (
        df
        .groupby(["StockCode", "Description"], dropna=False)
        .agg(
            Min_Date=("InvoiceDate", "min"),
            Max_Date=("InvoiceDate", "max"),
        )
        .reset_index()
    )

    product_date_range["Days_Active"] = (
        product_date_range["Max_Date"]
        - product_date_range["Min_Date"]
    ).dt.days

    # products active for 0 days
    zero_day_products = product_date_range[
        product_date_range["Days_Active"] == 0
    ].copy()

    # products active for 1–30 days
    short_duration_products = product_date_range[
        product_date_range["Days_Active"].between(1, 30)
    ].copy()

    # stock codes for short-duration products
    zero_day_stock_codes = set(
        zero_day_products["StockCode"]
    )

    short_duration_stock_codes = set(
        short_duration_products["StockCode"]
    )

    # product-level sales info
    product_sales = (
        df.groupby(["StockCode", "Description"], dropna=False)
        .agg(
            Units_Sold=("Quantity", "sum"),
            Revenue=("Revenue", "sum"),
            Customers=("CustomerID", "nunique"),
        )
        .reset_index()
    )

    # ad sales info to zero-day products
    zero_day_products = zero_day_products.merge(
        product_sales,
        on=["StockCode", "Description"],
        how="left",
    )

    # add sales info to 1–30 day products
    short_duration_products = short_duration_products.merge(
        product_sales,
        on=["StockCode", "Description"],
        how="left",
    )

    return (
        product_date_range,
        zero_day_products,
        short_duration_products,
        zero_day_stock_codes,
        short_duration_stock_codes,
    )

import pandas as pd


def analyze_product_duration(df):
    """
    Calculate the date range and number of active days for each product.
    """

    product_date_range = (
        df
        .groupby(["StockCode", "Description"], dropna=False)
        .agg(
            Min_Date=("InvoiceDate", "min"),
            Max_Date=("InvoiceDate", "max"),
        )
        .reset_index()
    )

    product_date_range["Days_Active"] = (
        product_date_range["Max_Date"]
        - product_date_range["Min_Date"]
    ).dt.days

    return product_date_range


def analyze_zero_day_products(df, product_date_range):
    """
    Identify products that were active for only one calendar day.
    """

    zero_day_products = product_date_range[
        product_date_range["Days_Active"] == 0
    ].copy()

    zero_day_stock_codes = set(
        zero_day_products["StockCode"]
    )

    return zero_day_products, zero_day_stock_codes


def analyze_product_reach(df, zero_day_stock_codes):
    """
    Calculate the number of unique customers who purchased
    each zero-day product.
    """

    zero_day_sales = df[
        df["StockCode"].isin(zero_day_stock_codes)
    ].copy()

    product_reach = (
        zero_day_sales
        .groupby(["StockCode", "Description"], dropna=False)
        .agg(
            Customers=("CustomerID", "nunique"),
            Units_Sold=("Quantity", "sum"),
        )
        .reset_index()
        .sort_values("Customers", ascending=False)
    )

    return product_reach


def analyze_zero_day_revenue(df, zero_day_stock_codes):
    """
    Calculate revenue generated by zero-day products.
    """

    zero_day_sales = df[
        df["StockCode"].isin(zero_day_stock_codes)
    ].copy()

    zero_day_revenue = (
        zero_day_sales["Revenue"]
        .sum()
    )

    return zero_day_revenue


def analyze_high_value_zero_day_participation(
    df,
    zero_day_stock_codes,
    high_value_customers,
):
    """
    Analyze high-value customer participation in zero-day products.
    """

    zero_day_sales = df[
        df["StockCode"].isin(zero_day_stock_codes)
    ].copy()

    high_value_ids = set(high_value_customers.index)

    zero_day_sales["Customer_Type"] = (
        zero_day_sales["CustomerID"]
        .isin(high_value_ids)
        .map({
            True: "High-Value",
            False: "Other"
        })
    )

    participation = (
        zero_day_sales
        .groupby("Customer_Type")
        .agg(
            Customers=("CustomerID", "nunique"),
            Revenue=("Revenue", "sum"),
            Units_Sold=("Quantity", "sum"),
        )
    )

    return participation
